package MapserviceDB;
// Generated Sep 10, 2014 4:21:53 PM by Hibernate Tools 3.6.0



/**
 * Hospitals generated by hbm2java
 */
public class Hospitals  implements java.io.Serializable {


     private Integer id;
     private String hospitalName;
     private String hospitalplace;
     private String hospitalPhone;
     private String hospitalEmail;

    public Hospitals() {
    }

	
    public Hospitals(String hospitalName, String hospitalplace) {
        this.hospitalName = hospitalName;
        this.hospitalplace = hospitalplace;
    }
    public Hospitals(String hospitalName, String hospitalplace, String hospitalPhone, String hospitalEmail) {
       this.hospitalName = hospitalName;
       this.hospitalplace = hospitalplace;
       this.hospitalPhone = hospitalPhone;
       this.hospitalEmail = hospitalEmail;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getHospitalName() {
        return this.hospitalName;
    }
    
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName;
    }
    public String getHospitalplace() {
        return this.hospitalplace;
    }
    
    public void setHospitalplace(String hospitalplace) {
        this.hospitalplace = hospitalplace;
    }
    public String getHospitalPhone() {
        return this.hospitalPhone;
    }
    
    public void setHospitalPhone(String hospitalPhone) {
        this.hospitalPhone = hospitalPhone;
    }
    public String getHospitalEmail() {
        return this.hospitalEmail;
    }
    
    public void setHospitalEmail(String hospitalEmail) {
        this.hospitalEmail = hospitalEmail;
    }




}


